name: Build and upload to PyPI

on:
  push:
    tags:
      - "*"

jobs:
  build_and_upload:
    name: Build and upload
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🔁
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Set up Python 🐍
        uses: actions/setup-python@bd6b4b6205c4dbad673328db7b31b7fab9e241c0 # v4.6.1
        with:
          python-version: "3.10"

      - name: Install Poetry and pre-commit 💈
        run: pip install poetry pre-commit

      - name: Install dependencies 🛠
        run: poetry install

      - name: Run pre-commit 🤔
        run: pre-commit run --all-files

      - name: Publish package to PyPI 🙌
        run: |
          set -e
          poetry config http-basic.pypi "__token__" "${PYPI_TOKEN}"
          poetry publish --build
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
